### ISSUE TITLE
`import throws AttributeError: 'NoneType' object has no attribute 'io'

### ISSUE THREAD

**Issue by ryu-bu** [CIDARLAB/pyLFR#47]
original code:
chemostat_chip.lfr:
```
`import nine_to_one_mux;

module chemostat_chip (
    finput [0:8] in,
    foutput out,
    control [0:5] c1, [0:9] c2
);

    flow after_mux;

    Nine_to_one nine_to_one_mux(in, after_mux, c1);

endmodule
```

nine_to_one_mux.lfr:
```
module nine_to_one_mux(
    finput [0:8] in,
    foutput out,
    control [0:5] c
);

    distribute@(c)
    begin
        case (c)
            6'b001001: out <= in[0];
            6'b001010: out <= in[1];
            6'b001100: out <= in[2];
            6'b010001: out <= in[3];
            6'b010010: out <= in[4];
            6'b010100: out <= in[5];
            6'b100001: out <= in[6];
            6'b100010: out <= in[7];
            6'b100100: out <= in[8];
        endcase
    end

endmodule
```

Error message:
```
Input Path: /workspaces/pyLFR/lfr-designs/nine_to_one_mux.lfr
Input Path: /workspaces/pyLFR/lfr-designs/chemostat_chip.lfr
File: /workspaces/pyLFR/lfr-designs/nine_to_one_mux.lfr
File: /workspaces/pyLFR/lfr-designs/chemostat_chip.lfr
['nine_to_one_mux.lfr', 'chemostat_chip.lfr']
output dir: out/
['nine_to_one_mux.lfr', 'chemostat_chip.lfr']
Initialized the lfrcompiler
Entering the Distribution Block
Entering the dis assign stat
Exiting the dist assign stat
LHS, RHS sizes are equal
Name: in_0, Type : IOType.FLOW_INPUT Name: out, Type : IOType.FLOW_OUTPUT
Could not find source - in_0 in state table connectivity graph, adding node
Could not find target - out in state table connectivity graph, adding node
Added the edge in_0 -> out
Entering the dis assign stat
Exiting the dist assign stat
LHS, RHS sizes are equal
Name: in_1, Type : IOType.FLOW_INPUT Name: out, Type : IOType.FLOW_OUTPUT
Could not find source - in_1 in state table connectivity graph, adding node
Could not find target - out in state table connectivity graph, adding node
Added the edge in_1 -> out
Entering the dis assign stat
Exiting the dist assign stat
LHS, RHS sizes are equal
Name: in_2, Type : IOType.FLOW_INPUT Name: out, Type : IOType.FLOW_OUTPUT
Could not find source - in_2 in state table connectivity graph, adding node
Could not find target - out in state table connectivity graph, adding node
Added the edge in_2 -> out
Entering the dis assign stat
Exiting the dist assign stat
LHS, RHS sizes are equal
Name: in_3, Type : IOType.FLOW_INPUT Name: out, Type : IOType.FLOW_OUTPUT
Could not find source - in_3 in state table connectivity graph, adding node
Could not find target - out in state table connectivity graph, adding node
Added the edge in_3 -> out
Entering the dis assign stat
Exiting the dist assign stat
LHS, RHS sizes are equal
Name: in_4, Type : IOType.FLOW_INPUT Name: out, Type : IOType.FLOW_OUTPUT
Could not find source - in_4 in state table connectivity graph, adding node
Could not find target - out in state table connectivity graph, adding node
Added the edge in_4 -> out
Entering the dis assign stat
Exiting the dist assign stat
LHS, RHS sizes are equal
Name: in_5, Type : IOType.FLOW_INPUT Name: out, Type : IOType.FLOW_OUTPUT
Could not find source - in_5 in state table connectivity graph, adding node
Could not find target - out in state table connectivity graph, adding node
Added the edge in_5 -> out
Entering the dis assign stat
Exiting the dist assign stat
LHS, RHS sizes are equal
Name: in_6, Type : IOType.FLOW_INPUT Name: out, Type : IOType.FLOW_OUTPUT
Could not find source - in_6 in state table connectivity graph, adding node
Could not find target - out in state table connectivity graph, adding node
Added the edge in_6 -> out
Entering the dis assign stat
Exiting the dist assign stat
LHS, RHS sizes are equal
Name: in_7, Type : IOType.FLOW_INPUT Name: out, Type : IOType.FLOW_OUTPUT
Could not find source - in_7 in state table connectivity graph, adding node
Could not find target - out in state table connectivity graph, adding node
Added the edge in_7 -> out
Entering the dis assign stat
Exiting the dist assign stat
LHS, RHS sizes are equal
Name: in_8, Type : IOType.FLOW_INPUT Name: out, Type : IOType.FLOW_OUTPUT
Could not find source - in_8 in state table connectivity graph, adding node
Could not find target - out in state table connectivity graph, adding node
Added the edge in_8 -> out
Exit the Distribution Block
Implement the fig generation from this
Connectivity table for the distribution block
╒═════════════╤═════════════╤═════════════╤═════════════╤═════════════╤═════════════╤═════════════╤═════════════╤═════════════╕
│   in_0->out │   in_1->out │   in_2->out │   in_3->out │   in_4->out │   in_5->out │   in_6->out │   in_7->out │   in_8->out │
╞═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│           1 │           0 │           0 │           0 │           0 │           0 │           0 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           1 │           0 │           0 │           0 │           0 │           0 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           1 │           0 │           0 │           0 │           0 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           0 │           1 │           0 │           0 │           0 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           0 │           0 │           1 │           0 │           0 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           0 │           0 │           0 │           1 │           0 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           0 │           0 │           0 │           0 │           1 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           0 │           0 │           0 │           0 │           0 │           1 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           0 │           0 │           0 │           0 │           0 │           0 │           1 │
╘═════════════╧═════════════╧═════════════╧═════════════╧═════════════╧═════════════╧═════════════╧═════════════╧═════════════╛
DISTRIBUTE-AND CANDIDATES:
[]
╒═════════════╤═════════════╤═════════════╤═════════════╤═════════════╤═════════════╤═════════════╤═════════════╤═════════════╕
│   in_0->out │   in_1->out │   in_2->out │   in_3->out │   in_4->out │   in_5->out │   in_6->out │   in_7->out │   in_8->out │
╞═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│           1 │           0 │           0 │           0 │           0 │           0 │           0 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           1 │           0 │           0 │           0 │           0 │           0 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           1 │           0 │           0 │           0 │           0 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           0 │           1 │           0 │           0 │           0 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           0 │           0 │           1 │           0 │           0 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           0 │           0 │           0 │           1 │           0 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           0 │           0 │           0 │           0 │           1 │           0 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           0 │           0 │           0 │           0 │           0 │           1 │           0 │
├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
│           0 │           0 │           0 │           0 │           0 │           0 │           0 │           0 │           1 │
╘═════════════╧═════════════╧═════════════╧═════════════╧═════════════╧═════════════╧═════════════╧═════════════╧═════════════╛
[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]
[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]
DISTRIBUTE-OR CANDIDATES
[[0, 1, 2, 3, 4, 5, 6, 7, 8]]
Need to implement the generation of the OR annotation
Traceback (most recent call last):
  File "//.pyenv/versions/3.8.0/bin/lfr-compile", line 8, in <module>
    sys.exit(main())
  File "//.pyenv/versions/3.8.0/lib/python3.8/site-packages/lfr/cmdline.py", line 123, in main
    walker.walk(mapping_listener, tree)
  File "//.pyenv/versions/3.8.0/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 160, in walk
    self.walk(listener, child)
  File "//.pyenv/versions/3.8.0/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 160, in walk
    self.walk(listener, child)
  File "//.pyenv/versions/3.8.0/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 160, in walk
    self.walk(listener, child)
  [Previous line repeated 4 more times]
  File "//.pyenv/versions/3.8.0/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 161, in walk
    self.exitRule(listener, t)
  File "//.pyenv/versions/3.8.0/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 188, in exitRule
    ctx.exitRule(listener)
  File "//.pyenv/versions/3.8.0/lib/python3.8/site-packages/lfr/antlrgen/lfrXParser.py", line 2507, in exitRule
    listener.exitOrderedioblock(self)
  File "//.pyenv/versions/3.8.0/lib/python3.8/site-packages/lfr/moduleinstanceListener.py", line 55, in exitOrderedioblock
    module_io = self._module_to_import.io
AttributeError: 'NoneType' object has no attribute 'io'
```

commands used:
```
lfr-compile --no-gen nine_to_one_mux.lfr chemostat_chip.lfr
```

**Comment by ryu-bu** [comment]
i flipped the type name and instance name by accident.
